source: J0605+3757
par-directory: results/
tim-directory: /nanograv/timing/releases/15y/toagen/releases/2021.04.21-9eefb99/
timing-model: J0605+3757_PINT_20210304.nb.par
compare-model: archive/J0605+3757.14yrbw.par
toas:
- J0605+3757.Rcvr1_2.GUPPI.15y.x.nb.tim
- J0605+3757.Rcvr_800.GUPPI.15y.x.nb.tim

free-params: [ELONG, ELAT, PMELONG, PMELAT, PX, F0, F1, A1, PB, T0, E, OM, JUMP1]
free-dmx: Yes
toa-type: NB
fitter: DownhillGLSFitter
n-iterations: 20
ephem: DE440
bipm: BIPM2019

dmx:  # control dmx windowing/fixing
  ignore-dmx: false
  fratio: 1.1
  max-sw-delay: 0.1 # finer binning when solar wind delay > threshold (us)
  custom-dmx: [] # designated by [mjd_low,mjd_hi,binsize]
outlier: # control outlier analysis runs
  method: gibbs
  n-burn: 1000
  n-samples: 20000

intermediate-results: # use results from previous runs
  noise-dir: /nanograv/share/15yr/timing/intermediate/noise-chains/
  excised-tim: /nanograv/share/15yr/timing/intermediate/outlier-2021.08/J0605+3757.nb/J0605+3757.nb_excise.tim
ignore: # toa excision
  mjd-start:
  mjd-end: 59072.0
  snr-cut: 8
  bad-toa:
  bad-range:
  bad-file:
  prob-outlier: 0.1

changelog:
- '2020-12-09 scott.ransom INIT: YAML autogenerated by write_initial_configs.py'
- '2021-03-05 anne.archibald READY_FOR: v0.9'
- '2021-08-24 joe.swiggum CURATE: no manual cuts to inspect'
