source: J0605+3757
par-directory: results/
tim-directory: /nanograv/timing/releases/15y/toagen/releases/2021.08.25-9d8d617/
timing-model: J0605+3757_PINT_20220121.nb.par
compare-model: archive/J0605+3757_PINT_20220112.nb.par
toas:
- J0605+3757.Rcvr1_2.GUPPI.15y.x.nb.tim
- J0605+3757.Rcvr_800.GUPPI.15y.x.nb.tim

free-params: [ELONG, ELAT, PMELONG, PMELAT, PX, F0, F1, A1, PB, T0, E, OM, JUMP1]
free-dmx: Yes
toa-type: NB
fitter: DownhillGLSFitter
n-iterations: 20
ephem: DE440
bipm: BIPM2019

dmx:  # control dmx windowing/fixing
  ignore-dmx: false
  fratio: 1.1
  max-sw-delay: 0.1 # finer binning when solar wind delay > threshold (us)
  custom-dmx: [] # designated by [mjd_low,mjd_hi,binsize]
outlier: # control outlier analysis runs
  method: gibbs
  n-burn: 1000
  n-samples: 20000

intermediate-results: # use results from previous runs
  noise-dir: /nanograv/share/15yr/timing/intermediate/20220121.Noise.nb.c58ebf3/
  compare-noise-dir: /nanograv/share/15yr/timing/intermediate/20220112.Noise.nb.cd80e4d/
  excised-tim: /nanograv/share/15yr/timing/intermediate/20211217.Outlier.nb.8551468/J0605+3757.nb/J0605+3757.nb_excise.tim
  no-corner: true
ignore: # toa excision
  mjd-start:
  mjd-end: 59072.0
  snr-cut: 8
  bad-toa:
  bad-range:
  bad-file:
  prob-outlier: 0.1

check:  # check before final
  toa-outliers:
  dmx-outliers:
  unusual-params:
  other:
  cleared: true
changelog:
- '2020-12-09 scott.ransom INIT: YAML autogenerated by write_initial_configs.py'
- '2021-03-05 anne.archibald READY_FOR: v0.9'
- '2021-08-24 joe.swiggum CURATE: no manual cuts to inspect'
- '2021-09-22 ingrid.stairs READY_FOR: v1.0'
- '2021-09-24 joe.swiggum NOTE: updated AO/GBO coords (pint v0.8.3) and refit'
- '2021-09-30 joe.swiggum NOTE: par file handed off to DWG for v1.0 is J0605+3757_PINT_20210928.nb.par'
